### ISSUE TITLE
Test Rom segfaults on qt and sdl frontend

### ISSUE THREAD

**Issue by destoer** [fleroviux/NanoboyAdvance#131] opened 2020-09-06 22:31 UTC
[dma_priority3.zip](https://github.com/fleroviux/NanoboyAdvance/files/5180390/dma_priority3.zip)

**Comment by fleroviux** [comment] 2020-11-21 15:27
This was caused by an assertion for unpredictable LDRD / STRD opcodes and should be resolved with https://github.com/fleroviux/NanoboyAdvance/commit/e559346cb654495f0cab10aa787a2e6e1d632656

**Closed by fleroviux** 2020-11-21 15:27 UTC
